apiVersion: v1
kind: Service
metadata:
 labels:
   app: spring
 name: spring
spec:
 externalTrafficPolicy: Cluster
 ports:
 - port: 8080
   protocol: TCP
   targetPort: 8080
 selector:
   app: spring
 sessionAffinity: None
 type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: spring-deployment
 labels:
   app: spring
spec:
 replicas: 3
 selector:
   matchLabels:
     app: spring
 template:
   metadata:
     labels:
       app: spring
   spec:
     containers:
     - name: spring
       image: docker.io/rla8127/demo-scg:v
       ports:
       - containerPort: 8080
